[build-system]
requires = ["setuptools>=69", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "hrm-kermanshah"
version = "0.3.0a1"
description = "HRM native desktop platform for Kermanshah Electricity Distribution"
requires-python = ">=3.11"
dependencies = [
  "cryptography==50.0.1",
  "PySide6==6.11.2",
]

[project.scripts]
sazmanhr-server = "sazmanhr.server:main"
sazmanhr-client = "sazmanhr.client:main"

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
