warning: in the working copy of '.github/workflows/windows-build.yml', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of '.gitignore', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'BUILD-SETUP.cmd', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'CHANGELOG.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'CI-LOCAL-VALIDATION.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'CI-PACKAGE-VERSION', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'CI-README-FA.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'PACKAGE-MANIFEST.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'PUSH-TO-GITHUB.cmd', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'README.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'SHA256SUMS.txt', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'TEST-REPORT.md', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'VERSION', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'build/windows/HRM.iss', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'build/windows/build_windows.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'build/windows/client.spec', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'build/windows/smoke-install.ps1', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'ci/write-ci-manifest.ps1', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'data/seed/manifest.json', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'src/sazmanhr/__init__.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'test-evidence/compile-check.log', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tests/test_ci_pipeline.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tests/test_package.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tools/build_release.py', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tools/collect-diagnostics.cmd', LF will be replaced by CRLF the next time Git touches it
warning: in the working copy of 'tools/create_icon.py', LF will be replaced by CRLF the next time Git touches it
