"use strict";
const state={token:sessionStorage.getItem("hrmToken")||"",me:null,current:null};
const $=id=>document.getElementById(id);
async function api(method,path,data){const h={"Accept":"application/json"};if(state.token)h.Authorization=`Bearer ${state.token}`;let body;if(data!==undefined){h["Content-Type"]="application/json";body=JSON.stringify(data)}const r=await fetch(path,{method,headers:h,body});let p={};try{p=await r.json()}catch{}if(!r.ok)throw new Error(p.error||`HTTP ${r.status}`);return p}
function esc(v){return String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[c]))}
function showApp(on){$("loginView").classList.toggle("hidden",on);$("appView").classList.toggle("hidden",!on)}
async function boot(){if(!state.token)return showApp(false);try{const me=await api("GET","/api/me");state.me=me;if(me.user.must_change_password){showApp(false);$("passwordForm").classList.remove("hidden");return}showApp(true);renderIdentity();await loadDashboard();}catch{state.token="";sessionStorage.removeItem("hrmToken");showApp(false)}}
$("loginForm").addEventListener("submit",async e=>{e.preventDefault();$("loginError").textContent="";try{const p=await api("POST","/api/login",{username:$("username").value,password:$("password").value,otp:$("otp").value});state.token=p.token;sessionStorage.setItem("hrmToken",p.token);$("currentPassword").value=$("password").value;await boot()}catch(err){$("loginError").textContent=err.message}});
$("passwordForm").addEventListener("submit",async e=>{e.preventDefault();try{await api("POST","/api/change-password",{current_password:$("currentPassword").value,new_password:$("newPassword").value});$("passwordForm").classList.add("hidden");await boot()}catch(err){$("loginError").textContent=err.message}});
$("logoutBtn").addEventListener("click",async()=>{try{await api("POST","/api/logout")}catch{}state.token="";sessionStorage.removeItem("hrmToken");location.reload()});
for(const b of document.querySelectorAll(".tabs [data-tab]"))b.addEventListener("click",async()=>{document.querySelectorAll(".tabs [data-tab]").forEach(x=>x.classList.toggle("active",x===b));document.querySelectorAll(".tab").forEach(x=>x.classList.toggle("active",x.id===b.dataset.tab));if(b.dataset.tab==="personnel")await loadPersonnel();if(b.dataset.tab==="audit")await loadAudit();if(b.dataset.tab==="users")await loadUsers()});
function renderIdentity(){const u=state.me.user,p=new Set(state.me.permissions);$("identity").innerHTML=`<b>${esc(u.display_name)}</b> — ${u.role==="owner"?"Super Admin":u.role==="admin"?"HR Admin":esc(u.role)}<br><span class="muted">${esc(u.username)} · ${p.size} دسترسی فعال</span>`;$("backupBtn").style.display=p.has("backup")?"":"none";document.querySelector('[data-tab="users"]').style.display=p.has("manage_users")?"":"none";document.querySelector('[data-tab="audit"]').style.display=p.has("view_audit")?"":"none"}
async function loadDashboard(){const d=await api("GET","/api/dashboard");const s=d.stats;$("stats").innerHTML=[["کل پرسنل",s.personnel],["فعال",s.active],["واحدها",s.units],["پست‌ها",s.positions],["بدون پست",s.unassigned],["Revision",s.revision]].map(x=>`<div class="stat">${x[0]}<strong>${esc(x[1])}</strong></div>`).join("")}
async function loadPersonnel(){const r=await api("GET","/api/personnel",undefined);renderPersonnel(r.items)}
async function searchPersonnel(){const q=$("search").value;const r=await api("GET",`/api/personnel?q=${encodeURIComponent(q)}&limit=200`);renderPersonnel(r.items)}
$("searchBtn").addEventListener("click",searchPersonnel);$("search").addEventListener("keydown",e=>{if(e.key==="Enter")searchPersonnel()});
function renderPersonnel(items){$("personnelRows").innerHTML=items.map(p=>`<tr data-id="${esc(p.id)}"><td>${esc(p.personnel_no)}</td><td>${esc(p.full_name)}</td><td>${esc(p.organizational_unit)}</td><td>${esc(p.position_title)}</td><td>${esc(p.status)}</td></tr>`).join("");for(const tr of $("personnelRows").querySelectorAll("tr"))tr.addEventListener("click",()=>loadPerson(tr.dataset.id))}
async function loadPerson(id){const [p,h]=await Promise.all([api("GET",`/api/personnel/${id}`),api("GET",`/api/personnel/${id}/movements`)]);state.current=p;const perm=new Set(state.me.permissions);const box=$("personDetail");box.innerHTML=`<h2>${esc(p.full_name)}</h2><div class="detail-grid"><div>شماره: <b>${esc(p.personnel_no)}</b></div><div>وضعیت: <b>${esc(p.status)}</b></div><div>واحد: <b>${esc(p.organizational_unit)}</b></div><div>پست: <b>${esc(p.position_title)}</b></div><div>کد پست: <b>${esc(p.position_code)}</b></div><div>محل: <b>${esc(p.actual_location)}</b></div></div><section class="history"><h3>سوابق جابه‌جایی</h3>${historyHtml(h.items,perm.has("reverse_movements"))}</section>`;for(const b of box.querySelectorAll("[data-reverse-movement]"))b.addEventListener("click",()=>reverseMovement(b.dataset.reverseMovement));if(perm.has("manage_movements")){const frag=$("movementTemplate").content.cloneNode(true);box.appendChild(frag);const f=box.querySelector("#movementForm");for(const k of ["organizational_unit","position_code","position_title","actual_location","status"])f.elements[k].value=p[k]||"";f.addEventListener("submit",submitMovement)}}
function historyHtml(items,canReverse=false){if(!items.length)return '<p class="muted">هنوز جابه‌جایی ثبت نشده است.</p>';let reverseOffered=false;return items.map(m=>{const action=canReverse&&!m.is_reversed&&!reverseOffered?(reverseOffered=true,`<br><button type="button" class="danger-inline" data-reverse-movement="${esc(m.id)}">ابطال این جابه‌جایی</button>`):"";return `<div class="event ${m.is_reversed?"reversed":""}"><b>${esc(m.movement_type)}</b> · ${esc(m.effective_date)}${m.order_no?` · حکم ${esc(m.order_no)}`:""}<br><span>${esc(m.reason||m.note||"")}</span>${m.is_reversed?`<br><b>ابطال:</b> ${esc(m.reversal_reason)}`:""}${action}</div>`}).join("")}
async function reverseMovement(id){const reason=prompt("علت ابطال آخرین جابه‌جایی را وارد کنید:");if(!reason||!reason.trim())return;if(!confirm("آخرین جابه‌جایی ابطال و وضعیت قبلی بازیابی شود؟"))return;try{await api("POST",`/api/movements/${encodeURIComponent(id)}/reverse`,{reason:reason.trim()});await loadPerson(state.current.id);await loadDashboard()}catch(err){alert(err.message)}}
async function submitMovement(e){e.preventDefault();const f=e.currentTarget,d=Object.fromEntries(new FormData(f).entries());d.row_version=state.current.row_version;try{const r=await api("POST",`/api/personnel/${state.current.id}/movements`,d);state.current=r.person;await loadPerson(state.current.id);await loadDashboard()}catch(err){alert(err.message)}}
$("backupBtn").addEventListener("click",async()=>{try{const r=await api("POST","/api/backup",{});alert(`Backup: ${r.filename}`)}catch(err){alert(err.message)}});
async function loadAudit(){try{const r=await api("GET","/api/audit?limit=100");$("auditRows").innerHTML=`<p>زنجیره ممیزی: <b>${r.chain_valid?"معتبر":"نامعتبر"}</b></p>`+r.items.map(a=>`<div class="event"><b>${esc(a.action)}</b> · ${esc(a.entity_type)} · ${esc(a.occurred_at)}</div>`).join("")}catch(err){$("auditRows").textContent=err.message}}
async function loadUsers(){try{const r=await api("GET","/api/users");$("userRows").innerHTML='<table><thead><tr><th>نام</th><th>کاربری</th><th>نقش</th><th>فعال</th></tr></thead><tbody>'+r.items.map(u=>`<tr><td>${esc(u.display_name)}</td><td>${esc(u.username)}</td><td>${u.role==="owner"?"Super Admin":u.role==="admin"?"HR Admin":esc(u.role)}</td><td>${u.is_active?"بله":"خیر"}</td></tr>`).join("")+'</tbody></table>'}catch(err){$("userRows").textContent=err.message}}
boot();
